// Chuỗi giao diện tiếng Việt tập trung một nơi.

export const labels = {
  siteName: "Hàn Ngữ",
  siteTagline: "Học tiếng Hàn theo giáo trình Tiếng Hàn Tổng Hợp",

  nav: {
    home: "Trang chủ",
    courses: "Khóa học",
    review: "Ôn tập",
    myCards: "Thẻ của tôi",
    progress: "Tiến độ",
    admin: "Quản trị",
    login: "Đăng nhập",
    register: "Đăng ký",
    logout: "Đăng xuất",
  },

  lesson: {
    vocabulary: "Từ vựng",
    grammar: "Ngữ pháp",
    dialogue: "Hội thoại",
    romanization: "Phiên âm",
    showRomanization: "Hiện phiên âm",
    hideRomanization: "Ẩn phiên âm",
    showTranslation: "Hiện bản dịch",
    hideTranslation: "Ẩn bản dịch",
    markComplete: "Đánh dấu hoàn thành",
    addToDeck: "Thêm từ vựng vào bộ thẻ",
    takeQuiz: "Làm bài kiểm tra",
    comingSoon: "Sắp ra mắt",
    stt: "STT",
    korean: "Tiếng Hàn",
    meaning: "Nghĩa",
    example: "Ví dụ",
    pattern: "Cấu trúc",
    explanation: "Giải thích",
    listening: "Luyện nghe",
    playAudio: "Phát âm",
    stopAudio: "Dừng phát",
    audioUnavailable: "Trình duyệt không hỗ trợ giọng đọc tiếng Hàn",
    flashcardPractice: "Flash card",
    showKorean: "Hiện tiếng Hàn",
    hideKorean: "Ẩn tiếng Hàn",
    slowSpeed: "Tốc độ chậm",
    playAll: "Phát toàn bộ",
  },

  listening: {
    dialogueTitle: "Nghe hội thoại",
    quizTitle: "Nghe và chọn nghĩa",
    quizIntro: "Nghe từ tiếng Hàn và chọn nghĩa tiếng Việt đúng.",
    start: "Bắt đầu",
    replay: "Nghe lại",
    needMoreVocab: "Bài học cần ít nhất 4 từ vựng để luyện nghe.",
    noDialogues: "Bài học này chưa có hội thoại.",
    question: (x: number, y: number) => `Câu ${x}/${y}`,
    result: (x: number, y: number) => `Đúng ${x}/${y} câu`,
  },

  auth: {
    loginTitle: "Đăng nhập",
    registerTitle: "Đăng ký tài khoản",
    name: "Họ tên",
    email: "Email",
    password: "Mật khẩu",
    confirmPassword: "Nhập lại mật khẩu",
    loginButton: "Đăng nhập",
    registerButton: "Đăng ký",
    loginWithGoogle: "Đăng nhập bằng Google",
    noAccount: "Chưa có tài khoản?",
    hasAccount: "Đã có tài khoản?",
    loginToTrack: "Đăng nhập để lưu tiến độ học tập của bạn",
    greeting: (name: string) => `Xin chào, ${name}!`,
  },

  progress: {
    completed: "Đã hoàn thành",
    completedLessons: (x: number, y: number) => `${x}/${y} bài`,
    percent: (p: number) => `${p}%`,
    totalCompleted: (n: number) => `Đã hoàn thành ${n} bài học`,
    dashboardTitle: "Tiến độ học tập",
    loginPrompt: "Đăng nhập để đánh dấu hoàn thành",
  },

  flashcard: {
    showAnswer: "Hiện đáp án",
    again: "Lại",
    hard: "Khó",
    good: "Tốt",
    easy: "Dễ",
    dueToday: (n: number) => `Hôm nay cần ôn ${n} thẻ`,
    empty: "Không còn thẻ nào đến hạn hôm nay 🎉",
    addedCards: (n: number) => `Đã thêm ${n} thẻ`,
    alreadyInDeck: "Từ vựng đã có trong bộ thẻ",
    autoAdded: "Đã thêm từ vựng vào bộ thẻ",
    remaining: (n: number) => `Còn ${n} thẻ`,
    sessionDone: "Hoàn thành phiên ôn tập!",
    reviewedCount: (n: number) => `Bạn đã ôn ${n} lượt thẻ`,
    known: "Đã thuộc",
    unknown: "Chưa thuộc",
    retryWrong: (n: number) => `Ôn lại ${n} thẻ chưa thuộc`,
    restart: "Học lại từ đầu",
    practiceDone: "Bạn đã thuộc tất cả từ vựng của bài! 🎉",
    practiceTitle: "Lật thẻ nhanh",
    flipHint: "Bấm để lật thẻ",

    // Ôn ghi nhớ ngắt quãng (SRS)
    srsTitle: "Ôn ghi nhớ",
    srsLessonTitle: (lesson: string) => `Ôn ghi nhớ — ${lesson}`,
    srsSavedNote: "Đánh giá của bạn được lưu vào lịch ôn ngắt quãng.",
    srsSeeDue: "Xem tất cả thẻ đến hạn hôm nay",

    // Chế độ lật thẻ nhanh (khách)
    quickTitle: (lesson: string) => `Lật thẻ nhanh — ${lesson}`,
    quickBanner:
      "Chế độ Lật thẻ nhanh — không lưu lịch ôn tập. Đăng nhập để bật Ôn ghi nhớ ngắt quãng (thẻ sẽ quay lại đúng lúc bạn sắp quên).",
    quickLogin: "Đăng nhập để bật Ôn ghi nhớ",

    // Trạng thái rỗng của /on-tap
    noCardsTitle: "Bắt đầu ôn ghi nhớ ngắt quãng",
    noCardsIntro:
      "Ôn ghi nhớ ngắt quãng (SRS) giúp bạn nhớ lâu: mỗi thẻ từ vựng sẽ quay lại đúng lúc bạn sắp quên. Thêm từ vựng của một bài vào bộ thẻ để bắt đầu.",
    noCardsHowTo:
      'Mở một bài học và bấm "Thêm từ vựng vào bộ thẻ", hoặc vào phần Flashcard của bài.',
    chooseLesson: "Chọn bài để bắt đầu",
    comeBackTomorrow: "Quay lại ngày mai để ôn tiếp nhé.",
    nextDue: (when: string) => `Thẻ tiếp theo đến hạn: ${when}`,
    createYourOwn: "➕ Tạo thẻ của bạn",
  },

  myCards: {
    title: "Thẻ của tôi",
    subtitle: "Thẻ tự tạo của bạn cùng ôn ngắt quãng với thẻ từ bài học.",
    create: "Tạo thẻ mới",
    korean: "Tiếng Hàn",
    romanization: "Phiên âm",
    vietnamese: "Nghĩa tiếng Việt",
    exampleKr: "Ví dụ (Hàn)",
    exampleVi: "Ví dụ (Việt)",
    optional: "(tùy chọn)",
    save: "Lưu thẻ",
    saving: "Đang lưu...",
    saved: "Đã lưu ✓",
    edit: "Sửa",
    delete: "Xóa",
    cancel: "Hủy",
    deleteConfirm: "Xóa thẻ này khỏi bộ ôn tập của bạn?",
    count: (n: number) => `${n} thẻ tự tạo`,
    reviewNow: "Ôn tập ngay",
    empty: "Bạn chưa tạo thẻ nào. Hãy tạo thẻ đầu tiên ở bên trên!",
  },

  quiz: {
    title: "Bài kiểm tra",
    progress: (x: number, y: number) => `Câu ${x}/${y}`,
    submit: "Nộp bài",
    result: (x: number, y: number) => `Kết quả: ${x}/${y} câu đúng`,
    retry: "Làm lại",
    next: "Câu tiếp →",
    prev: "← Câu trước",
    fillBlankPlaceholder: "Nhập câu trả lời...",
    yourAnswer: "Bạn trả lời",
    correctAnswer: "Đáp án đúng",
    notAnswered: "(bỏ trống)",
    noQuestions: "Bài học này chưa có câu hỏi kiểm tra.",
    history: "Lịch sử làm bài",
    historyEmpty: "Bạn chưa làm bài kiểm tra nào.",
  },

  admin: {
    dashboard: "Bảng điều khiển",
    areaTitle: "Khu vực quản trị",
    courses: "Quản lý khóa học",
    course: "Khóa học",
    lessons: "Bài học",
    vocab: "Từ vựng",
    grammar: "Ngữ pháp",
    dialogues: "Hội thoại",
    questions: "Câu hỏi",
    users: "Người dùng",
    attempts: "Lượt làm bài",
    add: "Thêm mới",
    edit: "Sửa",
    delete: "Xóa",
    save: "Lưu",
    saving: "Đang lưu...",
    saved: "Đã lưu ✓",
    cancel: "Hủy",
    audioUrl: "URL âm thanh (MP3, tùy chọn)",
    confirmDeleteCourse:
      "Xóa khóa học sẽ xóa toàn bộ bài học, từ vựng, thẻ ghi nhớ liên quan. Bạn chắc chắn?",
    confirmDeleteLesson:
      "Xóa bài học sẽ xóa toàn bộ từ vựng, ngữ pháp, hội thoại, câu hỏi và thẻ liên quan. Bạn chắc chắn?",
    confirmDeleteItem: "Bạn chắc chắn muốn xóa mục này?",
    title: "Tiêu đề",
    slug: "Slug (đường dẫn)",
    description: "Mô tả",
    order: "Thứ tự",
    openEditor: "Soạn nội dung →",
    backToAdmin: "← Quản trị",
  },

  levels: {
    soCap: "Sơ cấp",
    trungCap: "Trung cấp",
    caoCap: "Cao cấp",
  },

  common: {
    lessonCount: (n: number) => `${n} bài học`,
    startLearning: "Bắt đầu học",
    viewCourses: "Xem khóa học",
    backToCourse: "Quay lại khóa học",
    lesson: "Bài",
    notFound: "Không tìm thấy nội dung",
  },
} as const;
